"""empty message

Revision ID: 1c7057bf586f
Revises: 25fba478f8c0
Create Date: 2025-01-07 16:58:44.824381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7057bf586f'
down_revision = '25fba478f8c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
