"""empty message

Revision ID: 7920e615dc2c
Revises: 3f8fd424ac9a
Create Date: 2025-01-07 19:15:55.436663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7920e615dc2c'
down_revision = '3f8fd424ac9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('stock_available', sa.Integer(), nullable=True),
    sa.Column('units_sold', sa.Integer(), nullable=True),
    sa.Column('customer_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('demand_forecast', sa.Integer(), nullable=True),
    sa.Column('optimized_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('idx_category', 'products', ['category'], unique=False)
    op.create_index('idx_cost_price', 'products', ['cost_price'], unique=False)
    op.create_index('idx_customer_rating', 'products', ['customer_rating'], unique=False)
    op.create_index('idx_demand_forecast', 'products', ['demand_forecast'], unique=False)
    op.create_index('idx_name', 'products', ['name'], unique=False)
    op.create_index('idx_optimized_price', 'products', ['optimized_price'], unique=False)
    op.create_index('idx_selling_price', 'products', ['selling_price'], unique=False)
    op.create_index('idx_stock_available', 'products', ['stock_available'], unique=False)
    op.create_index('idx_units_sold', 'products', ['units_sold'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_units_sold', table_name='products')
    op.drop_index('idx_stock_available', table_name='products')
    op.drop_index('idx_selling_price', table_name='products')
    op.drop_index('idx_optimized_price', table_name='products')
    op.drop_index('idx_name', table_name='products')
    op.drop_index('idx_demand_forecast', table_name='products')
    op.drop_index('idx_customer_rating', table_name='products')
    op.drop_index('idx_cost_price', table_name='products')
    op.drop_index('idx_category', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
