"""empty message

Revision ID: 7d7fa19423de
Revises: 1c7057bf586f
Create Date: 2025-01-07 17:00:19.324961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7fa19423de'
down_revision = '1c7057bf586f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
