"""empty message

Revision ID: c8d397ab49ca
Revises: 18ac54cee13c
Create Date: 2025-01-08 14:09:33.945649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d397ab49ca'
down_revision = '18ac54cee13c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('module', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'module')
    # ### end Alembic commands ###
